In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Training/dataset1(NLP).csv')

In [4]:
df

                                   Message Label
0                         Hi, how are you?   Ham
1                     Let's meet tomorrow.   Ham
2             Call me when you reach home.   Ham
3           Good Morning! Have a nice day.   Ham
4               Can we meet at 5 PM today?   Ham
5           Please send me the assignment.   Ham
6    Happy Birthday! Have a wonderful day.   Ham
7                     I'll call you later.   Ham
8      Congratulations! You won a lottery.  Spam
9               Claim your free prize now.  Spam
10         Win cash by clicking this link.  Spam
11          Free recharge available today.  Spam
12          Limited time offer. Click now!  Spam
13             You have won a free iPhone.  Spam
14                   Buy one get one free.  Spam
15  Urgent! Claim your reward immediately.  Spam
16           Exclusive offer just for you.  Spam
17  Click here to receive your cash prize.  Spam
18                     Your OTP is 456789.   Ham
19                Thank you for your help.   Ham

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Message  20 non-null     object
 1   Label    20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

Message    0
Label      0
dtype: int64

In [8]:
import nltk
nltk.download('punkt_tab') # Tokenisation
nltk.download('stopwords') # Removal of Stop Words
nltk.download('wordnet') # Lemmatisation

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer # Stemming
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

Tokenisation

In [9]:
df['tokens'] = df['Message'].apply(word_tokenize)
df['tokens']

0                            [Hi, ,, how, are, you, ?]
1                         [Let, 's, meet, tomorrow, .]
2                [Call, me, when, you, reach, home, .]
3            [Good, Morning, !, Have, a, nice, day, .]
4                 [Can, we, meet, at, 5, PM, today, ?]
5               [Please, send, me, the, assignment, .]
6     [Happy, Birthday, !, Have, a, wonderful, day, .]
7                        [I, 'll, call, you, later, .]
8        [Congratulations, !, You, won, a, lottery, .]
9                   [Claim, your, free, prize, now, .]
10            [Win, cash, by, clicking, this, link, .]
11               [Free, recharge, available, today, .]
12            [Limited, time, offer, ., Click, now, !]
13                [You, have, won, a, free, iPhone, .]
14                       [Buy, one, get, one, free, .]
15    [Urgent, !, Claim, your, reward, immediately, .]
16               [Exclusive, offer, just, for, you, .]
17    [Click, here, to, receive, your, cash, prize, .]
18                          [Your, OTP, is, 456789, .]
19                    [Thank, you, for, your, help, .]
Name: tokens, dtype: object

Stop Word Removal

In [10]:
stop_words = set(stopwords.words("english"))

filtered_tokens = []

for token in df["tokens"]:
    temp = []

    for word in token:
        if word.lower() not in stop_words:
            temp.append(word)

    filtered_tokens.append(temp)

df["Filtered_Tokens"] = filtered_tokens

print(df["Filtered_Tokens"])

0                                     [Hi, ,, ?]
1                   [Let, 's, meet, tomorrow, .]
2                         [Call, reach, home, .]
3               [Good, Morning, !, nice, day, .]
4                        [meet, 5, PM, today, ?]
5                  [Please, send, assignment, .]
6        [Happy, Birthday, !, wonderful, day, .]
7                          ['ll, call, later, .]
8               [Congratulations, !, lottery, .]
9                        [Claim, free, prize, .]
10                [Win, cash, clicking, link, .]
11         [Free, recharge, available, today, .]
12           [Limited, time, offer, ., Click, !]
13                             [free, iPhone, .]
14                 [Buy, one, get, one, free, .]
15    [Urgent, !, Claim, reward, immediately, .]
16                         [Exclusive, offer, .]
17              [Click, receive, cash, prize, .]
18                              [OTP, 456789, .]
19                              [Thank, help, .]
Name: Filtered_Tokens, dtype: object

Stemming

In [11]:
stemmer = PorterStemmer()

stemmed_tokens = []

for token in df["Filtered_Tokens"]:
    temp = []

    for word in token:
      temp.append(PorterStemmer().stem(word))

    stemmed_tokens.append(temp)

df["Stemmed_Tokens"] = stemmed_tokens

df["Stemmed_Tokens"]

0                                [hi, ,, ?]
1              [let, 's, meet, tomorrow, .]
2                    [call, reach, home, .]
3             [good, morn, !, nice, day, .]
4                   [meet, 5, pm, today, ?]
5                  [pleas, send, assign, .]
6      [happi, birthday, !, wonder, day, .]
7                     ['ll, call, later, .]
8                [congratul, !, lotteri, .]
9                   [claim, free, prize, .]
10              [win, cash, click, link, .]
11         [free, recharg, avail, today, .]
12        [limit, time, offer, ., click, !]
13                         [free, iphon, .]
14            [buy, one, get, one, free, .]
15    [urgent, !, claim, reward, immedi, .]
16                       [exclus, offer, .]
17          [click, receiv, cash, prize, .]
18                         [otp, 456789, .]
19                         [thank, help, .]
Name: Stemmed_Tokens, dtype: object

Lemmatization

In [12]:
lemmatizer = WordNetLemmatizer()

lemmatized_tokens = []

for token in df["Stemmed_Tokens"]:
    temp = []

    for word in token:
        temp.append(lemmatizer.lemmatize(word))

    lemmatized_tokens.append(temp)

df["Lemmatized_Tokens"] = lemmatized_tokens

print(df["Lemmatized_Tokens"])

0                                [hi, ,, ?]
1              [let, 's, meet, tomorrow, .]
2                    [call, reach, home, .]
3             [good, morn, !, nice, day, .]
4                   [meet, 5, pm, today, ?]
5                   [plea, send, assign, .]
6      [happi, birthday, !, wonder, day, .]
7                     ['ll, call, later, .]
8                [congratul, !, lotteri, .]
9                   [claim, free, prize, .]
10              [win, cash, click, link, .]
11         [free, recharg, avail, today, .]
12        [limit, time, offer, ., click, !]
13                         [free, iphon, .]
14            [buy, one, get, one, free, .]
15    [urgent, !, claim, reward, immedi, .]
16                       [exclus, offer, .]
17          [click, receiv, cash, prize, .]
18                         [otp, 456789, .]
19                         [thank, help, .]
Name: Lemmatized_Tokens, dtype: object

Tokens into Sentences

In [13]:
df["Processed_Message"] = df["Lemmatized_Tokens"].apply(lambda x: " ".join(x))

df[["Processed_Message", "Label"]]

                 Processed_Message Label
0                           hi , ?   Ham
1           let 's meet tomorrow .   Ham
2                call reach home .   Ham
3           good morn ! nice day .   Ham
4                meet 5 pm today ?   Ham
5               plea send assign .   Ham
6    happi birthday ! wonder day .   Ham
7                 'll call later .   Ham
8            congratul ! lotteri .  Spam
9               claim free prize .  Spam
10           win cash click link .  Spam
11      free recharg avail today .  Spam
12      limit time offer . click !  Spam
13                    free iphon .  Spam
14          buy one get one free .  Spam
15  urgent ! claim reward immedi .  Spam
16                  exclus offer .  Spam
17       click receiv cash prize .  Spam
18                    otp 456789 .   Ham
19                    thank help .   Ham

Text into Numbers

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["Processed_Message"])

y = df["Label"]

Splittion of Dataset

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

Training

In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Accuracy

In [17]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = knn.predict(X_test)

print("Accuracy =", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy = 0.8
              precision    recall  f1-score   support

         Ham       1.00      0.50      0.67         2
        Spam       0.75      1.00      0.86         3

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5

User Message Prediction

In [20]:
msg = input("Enter the message: ")

Enter the message: Hello! You have WON a Lottery.

In [21]:
tokens = word_tokenize(msg)

tokens = [word for word in tokens if word.lower() not in stop_words]

tokens = [stemmer.stem(word) for word in tokens]

tokens = [lemmatizer.lemmatize(word) for word in tokens]

processed_message = " ".join(tokens)

In [22]:
processed_message

'hello ! lotteri .'

In [23]:
message_vector = vectorizer.transform([processed_message])

Prediction

In [24]:
prediction = knn.predict(message_vector)

print("Prediction:", prediction[0])

if prediction[0] == "Spam":
    print("This message is SPAM.")
else:
    print("This message is HAM.")

Prediction: Spam
This message is SPAM.